/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#ebe8e2",
        "tertiary-container": "#596b69",
        "primary-container": "#9a5625",
        "on-primary": "#ffffff",
        "primary": "#7d3f0f",
        "outline": "#867369",
        "on-secondary-fixed": "#351000",
        "on-surface-variant": "#53443a",
        "on-surface": "#1c1c18",
        "inverse-on-surface": "#f3f0ea",
        "on-primary-fixed": "#311300",
        "on-background": "#1c1c18",
        "surface-dim": "#dcdad4",
        "tertiary": "#415351",
        "error": "#ba1a1a",
        "surface-container-low": "#f6f3ed",
        "tertiary-fixed": "#d3e6e3",
        "surface-tint": "#8f4d1d",
        "primary-fixed": "#ffdbc7",
        "surface-bright": "#fcf9f3",
        "secondary": "#914b27",
        "on-tertiary-fixed": "#0d1e1d",
        "on-tertiary-container": "#d8ebe8",
        "on-primary-container": "#ffe1d1",
        "surface": "#fcf9f3",
        "secondary-fixed-dim": "#ffb694",
        "on-tertiary-fixed-variant": "#394a48",
        "on-primary-fixed-variant": "#723606",
        "outline-variant": "#d9c2b6",
        "on-secondary-container": "#773714",
        "error-container": "#ffdad6",
        "surface-container": "#f0eee8",
        "surface-container-highest": "#e5e2dc",
        "on-error": "#ffffff",
        "background": "#fcf9f3",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#b7cac7",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e5e2dc",
        "inverse-surface": "#31312d",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdbcc",
        "secondary-container": "#fda377",
        "on-secondary-fixed-variant": "#743412",
        "primary-fixed-dim": "#ffb689",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb689",
        "canvas-ivory": "#F6F2EA",
        "terroir-clay": "#8C4723",
        "volcanic-stone": "#EDE7DE",
        "brand-red-clay": "#8C4723",
        "brand-agave-green": "#2F403E",
        "brand-copper": "#855C37",
        "brand-canvas": "#F7F4EE",
        "brand-volcanic": "#EDE7DE",
        "brand-charcoal": "#1A1615"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "32px",
        "container-max": "1280px",
        "margin-mobile": "24px",
        "margin-desktop": "64px",
        "section-gap": "200px"
      },
      fontFamily: {
        "cormorant": ["Cormorant Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "navigation": ["Montserrat", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "display-hero": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"]
      },
      fontSize: {
        "headline-md": ["36px", { "lineHeight": "44px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "navigation": ["13px", { "lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.25em", "fontWeight": "700" }],
        "display-hero": ["96px", { "lineHeight": "104px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-md": ["15px", { "lineHeight": "30px", "fontWeight": "400" }],
        "body-lg": ["17px", { "lineHeight": "34px", "letterSpacing": "0.02em", "fontWeight": "300" }],
        "headline-lg-mobile": ["44px", { "lineHeight": "52px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
